const PDFDocument = require("pdfkit");
const SosAlert     = require("../models/SosAlert");
const StaffLog      = require("../models/StaffLog");
const Camper        = require("../models/Camper");
const ZoneHeartbeat = require("../models/ZoneHeartbeat");

const COLORS = {
  teal:  "#00A887",
  red:   "#D9362B",
  amber: "#B9770E",
  dark:  "#0A0E17",
  gray:  "#6B7280",
  light: "#94A3B8",
};

function fmtTime(date) {
  return date ? new Date(date).toLocaleString("en-NG", {
    day: "2-digit", month: "short", year: "numeric",
    hour: "2-digit", minute: "2-digit", hour12: false,
  }) : "—";
}

// GET /api/reports/incident-summary?from=ISO&to=ISO
const incidentSummary = async (req, res) => {
  try {
    const from = req.query.from ? new Date(req.query.from) : new Date(0);
    const to   = req.query.to   ? new Date(req.query.to)   : new Date();

    const [alerts, logs, campers, zones] = await Promise.all([
      SosAlert.find({ createdAt: { $gte: from, $lte: to } }).sort({ createdAt: 1 }),
      StaffLog.find({ createdAt: { $gte: from, $lte: to } }).sort({ createdAt: 1 }),
      Camper.find().populate("family_id", "family_name"),
      ZoneHeartbeat.find(),
    ]);

    const camperByDevice = {};
    campers.forEach((c) => { if (c.device_id) camperByDevice[c.device_id] = c; });

    const doc = new PDFDocument({ size: "A4", margin: 50, bufferPages: true });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="campsafe-incident-report-${Date.now()}.pdf"`);
    doc.pipe(res);

    // ── Header ──────────────────────────────────────────────
    doc.fontSize(22).fillColor(COLORS.dark).font("Helvetica-Bold").text("CampSafe", { continued: true });
    doc.fontSize(22).fillColor(COLORS.teal).text(" Incident Report");
    doc.fontSize(9).fillColor(COLORS.gray).font("Helvetica")
      .text(`Generated by ${req.user.username} (${req.user.role}) · ${fmtTime(new Date())}`);
    doc.fontSize(9).fillColor(COLORS.gray)
      .text(`Period: ${fmtTime(from)}  →  ${fmtTime(to)}`);
    doc.moveDown(1);
    drawDivider(doc);

    // ── Summary stats ───────────────────────────────────────
    const resolvedCount = alerts.filter((a) => a.resolved).length;
    const unresolvedCount = alerts.length - resolvedCount;
    const totalCheckedIn = campers.filter((c) => c.checked_in).length;
    const totalOutOfCamp = campers.filter((c) => !c.in_camp).length;

    doc.moveDown(0.5);
    doc.fontSize(13).fillColor(COLORS.dark).font("Helvetica-Bold").text("Session Summary");
    doc.moveDown(0.3);

    const stats = [
      ["Total SOS Alerts", alerts.length],
      ["Resolved",          resolvedCount],
      ["Unresolved",        unresolvedCount],
      ["Campers Checked In", totalCheckedIn],
      ["Currently Out of Camp", totalOutOfCamp],
      ["Staff Actions Logged", logs.length],
    ];
    drawStatGrid(doc, stats);
    doc.moveDown(1);
    drawDivider(doc);

    // ── SOS Alerts section ──────────────────────────────────
    doc.moveDown(0.5);
    doc.fontSize(13).fillColor(COLORS.dark).font("Helvetica-Bold").text("SOS Alerts");
    doc.moveDown(0.3);

    if (alerts.length === 0) {
      doc.fontSize(10).fillColor(COLORS.gray).font("Helvetica").text("No SOS alerts in this period.");
    } else {
      alerts.forEach((a, i) => {
        const camper = camperByDevice[a.device_id];
        const name   = camper ? `${camper.first_name} ${camper.last_name}` : a.device_id;
        checkPageBreak(doc, 60);

        doc.fontSize(10).font("Helvetica-Bold").fillColor(a.resolved ? COLORS.dark : COLORS.red)
          .text(`${i + 1}. ${a.resolved ? "" : "⚠ "}${name}`, { continued: false });
        doc.fontSize(9).font("Helvetica").fillColor(COLORS.gray)
          .text(`   Device: ${a.device_id}  ·  Location: ${a.latitude?.toFixed(5)}, ${a.longitude?.toFixed(5)}`);
        doc.text(`   Triggered: ${fmtTime(a.createdAt)}`);
        if (a.resolved) {
          doc.fillColor(COLORS.teal).text(`   ✓ Resolved by ${a.resolved_by} at ${fmtTime(a.resolved_at)}`);
        } else {
          doc.fillColor(COLORS.red).text(`   ✗ UNRESOLVED`);
        }
        doc.moveDown(0.4);
      });
    }

    doc.moveDown(0.5);
    drawDivider(doc);

    // ── Out of camp section ─────────────────────────────────
    doc.moveDown(0.5);
    doc.fontSize(13).fillColor(COLORS.dark).font("Helvetica-Bold").text("Currently Out of Camp");
    doc.moveDown(0.3);

    const outCampers = campers.filter((c) => !c.in_camp);
    if (outCampers.length === 0) {
      doc.fontSize(10).fillColor(COLORS.gray).font("Helvetica").text("Everyone is accounted for in camp.");
    } else {
      outCampers.forEach((c) => {
        checkPageBreak(doc, 30);
        doc.fontSize(10).font("Helvetica-Bold").fillColor(COLORS.amber)
          .text(`${c.first_name} ${c.last_name}`, { continued: true });
        doc.font("Helvetica").fillColor(COLORS.gray)
          .text(`  —  left at ${fmtTime(c.left_camp_at)}  ·  ${c.family_id?.family_name || "no family"}`);
      });
    }

    doc.moveDown(0.5);
    drawDivider(doc);

    // ── Zone status ──────────────────────────────────────────
    doc.moveDown(0.5);
    doc.fontSize(13).fillColor(COLORS.dark).font("Helvetica-Bold").text("Infrastructure Zone Status");
    doc.moveDown(0.3);

    if (zones.length === 0) {
      doc.fontSize(10).fillColor(COLORS.gray).font("Helvetica").text("No zone sensor data available.");
    } else {
      zones.forEach((z) => {
        checkPageBreak(doc, 25);
        const statusColor = !z.online ? COLORS.gray : (z.gas || z.motion) ? COLORS.amber : COLORS.teal;
        const statusLabel = !z.online ? "OFFLINE" : z.gas ? "GAS DETECTED" : z.motion ? "MOTION" : "NOMINAL";
        doc.fontSize(10).font("Helvetica-Bold").fillColor(COLORS.dark)
          .text(z.zone_name, { continued: true });
        doc.font("Helvetica").fillColor(statusColor).text(`  —  ${statusLabel}`);
      });
    }

    doc.moveDown(0.5);
    drawDivider(doc);

    // ── Staff activity log ───────────────────────────────────
    doc.moveDown(0.5);
    doc.fontSize(13).fillColor(COLORS.dark).font("Helvetica-Bold").text("Staff Activity Log");
    doc.moveDown(0.3);

    if (logs.length === 0) {
      doc.fontSize(10).fillColor(COLORS.gray).font("Helvetica").text("No staff activity logged in this period.");
    } else {
      logs.forEach((log) => {
        checkPageBreak(doc, 25);
        doc.fontSize(9).font("Helvetica-Bold").fillColor(COLORS.dark)
          .text(`${fmtTime(log.createdAt)}  ·  ${log.username} (${log.role})`, { continued: false });
        doc.font("Helvetica").fillColor(COLORS.gray).text(`   ${log.detail}`);
        doc.moveDown(0.15);
      });
    }

    // ── Footer page numbers ───────────────────────────────────
    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i++) {
      doc.switchToPage(i);
      doc.fontSize(8).fillColor(COLORS.light)
        .text(`CampSafe Incident Report — Page ${i + 1} of ${range.count}`, 50, doc.page.height - 40, {
          align: "center", width: doc.page.width - 100,
        });
    }

    doc.end();
  } catch (err) {
    console.error("Report generation error:", err);
    if (!res.headersSent) res.status(500).json({ error: err.message });
  }
};

function drawDivider(doc) {
  doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor("#E2E8F0").stroke();
}

function drawStatGrid(doc, stats) {
  const colWidth = (doc.page.width - 100) / 3;
  let x = 50, y = doc.y;
  stats.forEach((stat, i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    const cx = 50 + col * colWidth;
    const cy = y + row * 42;

    doc.fontSize(16).font("Helvetica-Bold").fillColor(COLORS.dark)
      .text(String(stat[1]), cx, cy);
    doc.fontSize(8).font("Helvetica").fillColor(COLORS.gray)
      .text(stat[0], cx, cy + 20, { width: colWidth - 10 });
  });
  doc.y = y + Math.ceil(stats.length / 3) * 42 + 10;
}

function checkPageBreak(doc, neededHeight) {
  if (doc.y + neededHeight > doc.page.height - 60) {
    doc.addPage();
  }
}

module.exports = { incidentSummary };